# Generated by Django 5.1.3 on 2025-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_profile_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='candidates',
            field=models.CharField(blank=True, choices=[('C1', 'candidate1'), ('C2', 'candidate2'), ('C3', 'candidate3'), ('C4', 'candidate4')], default=None, max_length=2, null=True),
        ),
    ]
